name: ambulance_tracker
description: Aplikasi GPS Ambulan Tracker dengan OpenStreetMap
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_map: ^6.1.0  
  flutter_map_tile_caching: ^9.0.1
  path_provider: ^2.1.4
  latlong2: ^0.9.0     
  http: ^1.1.0         
  shared_preferences: ^2.2.0  
  provider: ^6.0.5    
  location: ^5.0.3     
  permission_handler: ^11.0.1  
  url_launcher: ^6.2.5            
  intl: ^0.19.0                   
  cupertino_icons: ^1.0.6
  http_parser: ^4.0.0
  dio: ^5.1.0
  mime: ^1.0.0 
  socket_io_client: ^2.0.0         
  image_picker: ^0.8.7+4   
  table_calendar: ^3.0.9
  flutter_analog_clock: ^1.0.3
  slide_digital_clock: ^1.0.3
  logger: ^2.5.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/madiun.png
    - assets/images/splash.png
    - assets/images/pindai.png
    - assets/images/dikbud.png
    - assets/images/login.png
    - assets/images/register.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  fullscreen: true 
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleToFill
  
  android_12:
    image: assets/images/screen.png
    color: "#ffffff"
    branding_mode: center
    android: true
    ios: true